# Let's Get This Snowball Rolling

Now, it's your turn to evaluate how a logistic regression model performs. This time, you’ll do so in the context of trying to help a fintech startup more quickly grow its user base. By applying the code you learned to customer data, you’ll discover how machine learning has the potential to turbocharge the growth trajectory of a fintech firm.

## Instructions

1. Read in the dataset about the current customers of the startup.

2. Split the data into X and y and then into testing and training sets.

3. Fit a logistic regression classifier.

4. Create the predicted values for the testing and the training data.

5. Print a confusion matrix for the training data.

6. Print a confusion matrix for the testing data.

7. Print the training classification report.

8. Print the testing classification report.

9. Answer the following question: How does the model performance compare between the training data and the testing data?


## Resources:

Following are links to modules from the scikit learn library that will be utilized:

[Logistic Regression](https://scikit-learn.org/stable/modules/generated/sklearn.linear_model.LogisticRegression.html)

[train_test_split](https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html)

[classifiction_report](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.classification_report.html)

[confusion_matrix](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.confusion_matrix.html)

In [2]:
import pandas as pd
from pathlib import Path

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

## Step 1: Read in the dataset about the current customers of the startup.

In [4]:
# Read the usage_stats.csv file from the Resources folder into a Pandas DataFrame
customer_df = pd.read_csv(
    Path("12.3/01-lets-get-this-snowball-rolling/Resources/usage_stats.csv")
)

# Review the DataFrame
display(customer_df.head())
display(customer_df.tail())

   Usage Stats  Referral History  Customer Rank  target
0     1.054075         -2.010163      -0.918689       0
1     2.033251         -0.212776      -2.947451       0
2     1.049233         -2.239878      -0.777080       0
3     0.837035         -1.926558      -1.113686       0
4     1.193770         -1.550953      -1.539586       0

      Usage Stats  Referral History  Customer Rank  target
1205     1.975540         -2.200099       0.345623       1
1206     2.093416         -1.592133      -1.300825       0
1207     2.010334         -1.758225      -1.173162       0
1208     4.451947         -0.502815      -2.355020       0
1209     2.141445         -1.993869      -0.946396       0

## Step 2: Split the data into X and y and then into testing and training sets.

In [5]:
# Split the data into X (features) and y (target)

# The y variable should focus on the target column
y = customer_df['target']

X = customer_df.drop(columns=['target'])
X.head()

   Usage Stats  Referral History  Customer Rank
0     1.054075         -2.010163      -0.918689
1     2.033251         -0.212776      -2.947451
2     1.049233         -2.239878      -0.777080
3     0.837035         -1.926558      -1.113686
4     1.193770         -1.550953      -1.539586

In [6]:
# Split into testing and training sets using train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y)

## Step 3: Fit a logistic regression classifier.

In [8]:
# Declare a logistic regression model.
# Apply a random_state of 9 to the model
logistic_regression_model = LogisticRegression(random_state=9)

# Fit and save the logistic regression model using the training data
lr_model = logistic_regression_model.fit(X_train,y_train)
lr_model

LogisticRegression(random_state=9)

## Step 4: Create the predicted values for the testing and the training data.

In [9]:
#Generate training predictions
training_predictions = lr_model.predict(X_train)

#Generate testing predictions
testing_predictions = logistic_regression_model.predict(X_test)

## Step 5: Print a confusion matrix for the training data.

In [10]:
# Import the model for sklearn's confusion matrix
from sklearn.metrics import confusion_matrix

# Create and save the confustion matrix for the training data
training_matrix = confusion_matrix(y_train, training_predictions)

print(training_matrix)

[[803   8]
 [ 16  80]]

## Step 6: Pring a confusion matrix for the texting data.

In [11]:
# Create and save the confustion matrix for the testing data
test_matrix = confusion_matrix(y_test,testing_predictions)

print(test_matrix)

[[275   3]
 [  3  22]]

## Step 7: Print the training classification report.

In [12]:
# Create and save the training classifiction report
training_report = classification_report(y_train, training_predictions)

print(training_report)

              precision    recall  f1-score   support

           0       0.98      0.99      0.99       811
           1       0.91      0.83      0.87        96

    accuracy                           0.97       907
   macro avg       0.94      0.91      0.93       907
weighted avg       0.97      0.97      0.97       907

## Step 8: Print the testing classification report.

In [13]:
# Create and save the testing classifiction report
testing_report = classification_report(y_test, testing_predictions)

print(testing_report)

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       278
           1       0.88      0.88      0.88        25

    accuracy                           0.98       303
   macro avg       0.93      0.93      0.93       303
weighted avg       0.98      0.98      0.98       303

## Step 9: Answer the following question

> **Question**: How does the performance of the training and test dataset compare?

> **Sample Answer**: Looking at the two classification reports for the training and test data, it looks as if model performance declined--albeit slightly--on the test data. This is to be expected: this is how well the model is performing on data that the model hasn't seen before. If we're still getting strong precision and recall on the test dataset, this is a good indication about how well the model is likely to perform in real life.