# Inspecting Time Zones in Stock Data

In this activity, you’ll load historical stock data from Tesla Motors (TSLA) to practice your `datetime` data transformation skills.

Instructions:

1. Read the Tesla historical stock data from the CSV file into a DataFrame.

2. Use the Pandas `head` function to inspect the data. Use the Pandas `info` function to check the data types of each column.

3. Convert the “time” column to the `datetime` data type by using the Pandas `to_datetime` function.

    > **Hint** Because the “time” column contains UTC `Timestamp` data, remember to set `utc=True`.

4. Use the Pandas `head` and `info` functions to verify the data type transformation and the time zone.

5. Convert the time zone to that of Berlin (`Europe/Berlin`), and verify the time zone transformation by using the Pandas `head` and `info` functions.


References:

[Pandas.to_datetime](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.to_datetime.html)

[Pandas.dt.tz_convert](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Series.dt.tz_convert.html)

[Python time zones](https://pvlib-python.readthedocs.io/en/stable/timetimezones.html)

In [1]:
import pandas as pd
from pathlib import Path

## Step 1: Read the Tesla historical stock data from the CSV file into a DataFrame.

In [3]:
# Read the data from the tsla_historical.csv file into a Pandas DataFrame
df_tsla = pd.read_csv(
    Path("11.1/01-Inspecting_Time_Zones_in_Stock_Data/Resources/tsla_historical.csv")
)
df_tsla.head()

                        time    close
0  2018-01-02 09:30:00-05:00  315.870
1  2018-01-02 09:45:00-05:00  317.500
2  2018-01-02 10:00:00-05:00  318.035
3  2018-01-02 10:15:00-05:00  317.470
4  2018-01-02 10:30:00-05:00  316.875

In [4]:
# Inspect the DataFrame's data types using the info function
df_tsla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21279 entries, 0 to 21278
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    21279 non-null  object
 1   close   21279 non-null  float64
dtypes: float64(1), object(1)
memory usage: 332.6+ KB

## Step 3: Convert the “time” column to the `datetime` data type by using the Pandas `to_datetime` function.

> **Hint** Because the “time” column contains UTC `Timestamp` data, remember to set `utc=True`.

In [9]:
df_tsla['time'] = pd.to_datetime(
    df_tsla['time'],
    #infer_datetime_format = True,
    utc = True
)

df_tsla.head()

                       time    close
0 2018-01-02 14:30:00+00:00  315.870
1 2018-01-02 14:45:00+00:00  317.500
2 2018-01-02 15:00:00+00:00  318.035
3 2018-01-02 15:15:00+00:00  317.470
4 2018-01-02 15:30:00+00:00  316.875

In [10]:
df_tsla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21279 entries, 0 to 21278
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    21279 non-null  datetime64[ns, UTC]
 1   close   21279 non-null  float64
dtypes: datetime64[ns, UTC](1), float64(1)
memory usage: 332.6 KB

## Step 5: Convert the time zone to that of Berlin (`Europe/Berlin`), and verify the time zone transformation by using the Pandas `head` and `info` functions.

In [11]:
# Convert the time column to the Europe/Berlin timezone
df_tsla['time'] = df_tsla['time'].dt.tz_convert('Europe/Berlin')

In [12]:
df_tsla.head()

                       time    close
0 2018-01-02 15:30:00+01:00  315.870
1 2018-01-02 15:45:00+01:00  317.500
2 2018-01-02 16:00:00+01:00  318.035
3 2018-01-02 16:15:00+01:00  317.470
4 2018-01-02 16:30:00+01:00  316.875

In [13]:
df_tsla.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21279 entries, 0 to 21278
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   time    21279 non-null  datetime64[ns, Europe/Berlin]
 1   close   21279 non-null  float64
dtypes: datetime64[ns, Europe/Berlin](1), float64(1)
memory usage: 332.6 KB